jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: metadata
      name: Dependabot metadata
      uses: dependabot/fetch-metadata@v1.3.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
        steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
      name: Approve Dependabot PRs
      run: gh pr review --approve "$PR_URL"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PR_URL: ${{github.event.pull_request.html_url}}
      if: ${{steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
        steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
      name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --rebase "$PR_URL"
name: Dependabot Auto Merge
on:
  repository_dispatch:
    types: trigger-ga___dependabot-auto-merge.yml
permissions:
  contents: write
  pull-requests: write
